run:
  timeout: 5m
  tests: true
  skip-dirs:
    - pkg/generated

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
