// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Arubacloud/sdk-go/internal/impl/auth/credentialsrepository/vault (interfaces: VaultClient,LogicalAPI,KvAPI,AuthAPI,AuthTokenAPI)
//
// Generated by this command:
//
//	mockgen -package vault -destination=zz_mock_vault_test.go github.com/Arubacloud/sdk-go/internal/impl/auth/credentialsrepository/vault VaultClient,LogicalAPI,KvAPI,AuthAPI,AuthTokenAPI
//

// Package vault is a generated GoMock package.
package vault

import (
	context "context"
	reflect "reflect"

	api "github.com/hashicorp/vault/api"
	gomock "go.uber.org/mock/gomock"
)

// MockVaultClient is a mock of VaultClient interface.
type MockVaultClient struct {
	ctrl     *gomock.Controller
	recorder *MockVaultClientMockRecorder
}

// MockVaultClientMockRecorder is the mock recorder for MockVaultClient.
type MockVaultClientMockRecorder struct {
	mock *MockVaultClient
}

// NewMockVaultClient creates a new mock instance.
func NewMockVaultClient(ctrl *gomock.Controller) *MockVaultClient {
	mock := &MockVaultClient{ctrl: ctrl}
	mock.recorder = &MockVaultClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVaultClient) EXPECT() *MockVaultClientMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockVaultClient) Auth() AuthAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(AuthAPI)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockVaultClientMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockVaultClient)(nil).Auth))
}

// KVv2 mocks base method.
func (m *MockVaultClient) KVv2(arg0 string) KvAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVv2", arg0)
	ret0, _ := ret[0].(KvAPI)
	return ret0
}

// KVv2 indicates an expected call of KVv2.
func (mr *MockVaultClientMockRecorder) KVv2(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVv2", reflect.TypeOf((*MockVaultClient)(nil).KVv2), arg0)
}

// Logical mocks base method.
func (m *MockVaultClient) Logical() LogicalAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logical")
	ret0, _ := ret[0].(LogicalAPI)
	return ret0
}

// Logical indicates an expected call of Logical.
func (mr *MockVaultClientMockRecorder) Logical() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logical", reflect.TypeOf((*MockVaultClient)(nil).Logical))
}

// SetNamespace mocks base method.
func (m *MockVaultClient) SetNamespace(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNamespace", arg0)
}

// SetNamespace indicates an expected call of SetNamespace.
func (mr *MockVaultClientMockRecorder) SetNamespace(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNamespace", reflect.TypeOf((*MockVaultClient)(nil).SetNamespace), arg0)
}

// SetToken mocks base method.
func (m *MockVaultClient) SetToken(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", arg0)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockVaultClientMockRecorder) SetToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockVaultClient)(nil).SetToken), arg0)
}

// MockLogicalAPI is a mock of LogicalAPI interface.
type MockLogicalAPI struct {
	ctrl     *gomock.Controller
	recorder *MockLogicalAPIMockRecorder
}

// MockLogicalAPIMockRecorder is the mock recorder for MockLogicalAPI.
type MockLogicalAPIMockRecorder struct {
	mock *MockLogicalAPI
}

// NewMockLogicalAPI creates a new mock instance.
func NewMockLogicalAPI(ctrl *gomock.Controller) *MockLogicalAPI {
	mock := &MockLogicalAPI{ctrl: ctrl}
	mock.recorder = &MockLogicalAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogicalAPI) EXPECT() *MockLogicalAPIMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockLogicalAPI) Write(arg0 string, arg1 map[string]any) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0, arg1)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockLogicalAPIMockRecorder) Write(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLogicalAPI)(nil).Write), arg0, arg1)
}

// MockKvAPI is a mock of KvAPI interface.
type MockKvAPI struct {
	ctrl     *gomock.Controller
	recorder *MockKvAPIMockRecorder
}

// MockKvAPIMockRecorder is the mock recorder for MockKvAPI.
type MockKvAPIMockRecorder struct {
	mock *MockKvAPI
}

// NewMockKvAPI creates a new mock instance.
func NewMockKvAPI(ctrl *gomock.Controller) *MockKvAPI {
	mock := &MockKvAPI{ctrl: ctrl}
	mock.recorder = &MockKvAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKvAPI) EXPECT() *MockKvAPIMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockKvAPI) Get(arg0 context.Context, arg1 string) (*api.KVSecret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*api.KVSecret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKvAPIMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKvAPI)(nil).Get), arg0, arg1)
}

// MockAuthAPI is a mock of AuthAPI interface.
type MockAuthAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAPIMockRecorder
}

// MockAuthAPIMockRecorder is the mock recorder for MockAuthAPI.
type MockAuthAPIMockRecorder struct {
	mock *MockAuthAPI
}

// NewMockAuthAPI creates a new mock instance.
func NewMockAuthAPI(ctrl *gomock.Controller) *MockAuthAPI {
	mock := &MockAuthAPI{ctrl: ctrl}
	mock.recorder = &MockAuthAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAPI) EXPECT() *MockAuthAPIMockRecorder {
	return m.recorder
}

// Token mocks base method.
func (m *MockAuthAPI) Token() AuthTokenAPI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(AuthTokenAPI)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockAuthAPIMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockAuthAPI)(nil).Token))
}

// MockAuthTokenAPI is a mock of AuthTokenAPI interface.
type MockAuthTokenAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenAPIMockRecorder
}

// MockAuthTokenAPIMockRecorder is the mock recorder for MockAuthTokenAPI.
type MockAuthTokenAPIMockRecorder struct {
	mock *MockAuthTokenAPI
}

// NewMockAuthTokenAPI creates a new mock instance.
func NewMockAuthTokenAPI(ctrl *gomock.Controller) *MockAuthTokenAPI {
	mock := &MockAuthTokenAPI{ctrl: ctrl}
	mock.recorder = &MockAuthTokenAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthTokenAPI) EXPECT() *MockAuthTokenAPIMockRecorder {
	return m.recorder
}

// RenewSelfWithContext mocks base method.
func (m *MockAuthTokenAPI) RenewSelfWithContext(arg0 context.Context, arg1 int) (*api.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenewSelfWithContext", arg0, arg1)
	ret0, _ := ret[0].(*api.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenewSelfWithContext indicates an expected call of RenewSelfWithContext.
func (mr *MockAuthTokenAPIMockRecorder) RenewSelfWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewSelfWithContext", reflect.TypeOf((*MockAuthTokenAPI)(nil).RenewSelfWithContext), arg0, arg1)
}
